### ISSUE TITLE
Folder entity, schema, associated with folder and UI that user can choose folders per mode

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#21]
- we should come up with a new data structure to store the latest message of each folder
- we should provide a way to execute scripts (mode) on multiple folders; right now we just assume users only use INBOX.

**Comment by lukesmurray** [comment]
This ties into the fact that we need to stop using UID as a id for messages since as soon as we start using multiple folders the UID is absolutely not guaranteed to be unique. 

ALSO

One thing we should do is document where we are using `select_folder` to select the inbox and figure out how we want to change those references. The other day I started messing around with this for `fetch_latest_email_id` and realized that this can get complicated. The correct way to actually fetch the latest email would involve looking in all the user's folders (except maybe ignore spam and trash). Here is some example code with nonrelevant parts omitted.

```python
def fetch_latest_email_id():
    # some code ...
    for folder_name in list_folder_names(imap_account, imap_client):
        imap_client.select_folder(folder_name)
   # more code ...
```

I realized when I was doing this that the final folder that we select with the imap_client isn't obvious to the user nor is it stored anywhere in our code. I looked at `ImapClient` and couldn't see any way to get the currently selected folder either. It might be something we want to keep track of. Also our `Message` objects might want to have a reference to the folder they are currently in, but that could get messy since they could be moved by another client and then we'd be out of sync.

**Comment by soyapark** [comment]
After I looked into IMAP doc, I'm actually convinced to keep using UID for keeping up with new incoming messages. Using UID seems like a widely used method: https://stackoverflow.com/questions/10076690/ruby-imap-changes-since-last-check

I can think of many good reasons why we should use UID (e.g., it only increments. Easy to find past and next emails etc.)

We can have a secondary method to make sure we don't miss a new email. 
One proposal is along with the UID, we can also save the arrival date of the latest email and compare the date.

**Comment by lukesmurray** [comment]
Interesting. Do we know if it only increments across folders as well? I assume that it does. 

The synchronization they mention is interesting. We should look into that.

**Comment by soyapark** [comment]
Every folder keeps its own independent incrementer

**Comment by soyapark** [comment]
Proposed UI for folder management per mode:
![image](https://user-images.githubusercontent.com/33616044/53464496-7484d800-3a18-11e9-9c95-675ebe3d2bc6.png)

**Comment by lukesmurray** [comment]
> Every folder keeps its own independent incrementer

This means that `fetch_latest_email_id` needs to operate at a folder level, and `ImapAccount.newestEmailId` needs to be stored at the folder level as well.

**Comment by lukesmurray** [comment]
The proposed UI looks like you can select multiple folders simultaneously. Note sure if we want that or not? Since this would require us to abstract away completely the fact that IMAP makes clients select a folder.

**Comment by soyapark** [comment]
I can imagine users might want to apply the same mode to multiple folders.
Engineering-wise, it is easy to implement. We just run the same code multiple times for selected folders of a mode.

**Comment by lukesmurray** [comment]
this ui doesn't deal with nested folders.

**Comment by soyapark** [comment]
It wasn't shown at the previous screenshot, but we will support nested folders using tree structures
<img width="551" alt="image" src="https://user-images.githubusercontent.com/33616044/53521138-5ca76580-3aa5-11e9-971f-73735b0eabbc.png">

**Comment by soyapark** [comment]
Currently, we assume we select folders before interpret().
However, there are some cases I need to access folders during interpret(), so we should add one more argument to interpret()?
