### ISSUE TITLE
beautify execution log

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#7]
Right now, execution log is one big chunk of texts. 
Should segment and present logs prettier.

**Comment by lukesmurray** [comment]
Just to document our conversation. We decided that we should only use file logs for our own debugging information, and thus we can use a console logger to output logs to the user.

We could then expose a log level to the user so that they can control the level of detail on their logs, to the point that they would only see error logs and their own print statements.

All stdout for user code would be captured in `StringIO` and returned to the user.
