### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#83]
Hidden (from git repo) project dependency
- cronjobs
```
# To reboot RabbitMQ once a day at 5am
0 5 * * * /home/ubuntu/production/mailx/rabbitmq_reboot.sh
# if we want to abandon celery and go back to old fashion 
#* * * * * python /home/ubuntu/production/mailx/manage.py mailbot
#* * * * * ( sleep 5 ; python /home/ubuntu/production/mailx/manage.py mailbot)
#* * * * * ( sleep 10 ; python /home/ubuntu/production/mailx/manage.py mailbot)
#* * * * * ( sleep 15 ; python /home/ubuntu/production/mailx/manage.py mailbot)
#* * * * * ( sleep 20 ; python /home/ubuntu/production/mailx/manage.py mailbot)
#* * * * * ( sleep 25 ; python /home/ubuntu/production/mailx/manage.py mailbot)
#* * * * * ( sleep 30 ; python /home/ubuntu/production/mailx/manage.py mailbot)
#* * * * * ( sleep 35 ; python /home/ubuntu/production/mailx/manage.py mailbot)
#* * * * * ( sleep 40 ; python /home/ubuntu/production/mailx/manage.py mailbot)
#* * * * * ( sleep 45 ; python /home/ubuntu/production/mailx/manage.py mailbot)
#* * * * * ( sleep 50 ; python /home/ubuntu/production/mailx/manage.py mailbot)
#* * * * * ( sleep 55 ; python /home/ubuntu/production/mailx/manage.py mailbot)
```
- Apache wsgi configuration at /etc/apache2/httpd-ssl.conf (if http,  /etc/apache2/httpd.conf)
- private.py
- logging files?

**Comment by lukesmurray** [comment]
1. What cron jobs are we currently using? Can we list them here?

2. `/etc/apache2/httpd-ssl.conf` doesn't even exist on the dev machine. I assume its because we are not using ssl certificates. Can we figure out the minimum files we need to add to `/etc/apache2/` in order to run the server.

3. Not sure what is hidden about mysql other than the fact that we use it. I think we are using default settings.

**Comment by lukesmurray** [comment]
Alright so I've been messing around with Apache2 for the first time and I've found some things.

These are the contents of `/etc/apache2`

```
├── apache2.conf
├── apache2.conf.dpkg-dist
├── conf-available
├── conf.d
├── conf-enabled
├── envvars
├── httpd.conf
├── magic
├── mods-available
├── mods-enabled
├── ports.conf
├── sites-available
├── sites-enabled
└── ssl
```

These are the things that look important

`httpd.conf` serves our application with the following virtual host definition. This relies on [mod_wsgi](https://modwsgi.readthedocs.io/en/develop/index.html) to be installed.

```
<VirtualHost *:80>
WSGIDaemonProcess mailx python-path=/home/ubuntu/production/mailx
WSGIScriptAlias / /home/ubuntu/production/mailx/http_handler/wsgi.py process-group=mailx application-group=%{GLOBAL}
Alias /static /home/ubuntu/production/mailx/http_handler/static
</VirtualHost>
```

If we are on the production server then I believe `sites-available/000-default.conf` has an effect. We can enable or disable the site with `sudo a2ensite 000-default` or `sudo a2dissite 000-default` followed by `sudo service apache2 reload`. The site does not have to be enabled on the dev server. Based on these files I'm actually not sure how we serve the site. Maybe we fallback on `httpd.conf` or these files are different on the production server.

```conf
# this might serve http content but the DocumentRoot is the default apache file
<VirtualHost *:80>
  ServerName youps.csail.mit.edu
  
  DocumentRoot /var/www/html
  
  <Directory /var/www/html>
    Allow from all
    Options -MultiViews
  </Directory>
</VirtualHost>

# this appears to serve the https content
<IfModule mod_ssl.c>
  <VirtualHost *:443>
    ServerName youps.csail.mit.edu
    
    DocumentRoot /var/www/html
    SSLEngine on
    SSLCertificateFile "/etc/apache2/ssl/youps.crt"
    SSLCertificateKeyFile "/etc/apache2/ssl/youps.key"
    ErrorLog ${APACHE_LOG_DIR}/calendar.error.log
    CustomLog ${APACHE_LOG_DIR}/calendar.access.log combined
    
    
  </VirtualHost>
</IfModule>
```

Our crt and csr files are in the `ssl` directory. Since these certs are registered to the production server they are invalid on the dev server.

In `/etc/hosts` we appare to have our mail server set up.

```
128.52.161.210  mailx.csail.mit.edu     mailx
```
